#!/usr/bin/env python3
"""AWS IAM Least Privilege Report Summarizer.

Reads JSON reports generated by scan.py and produces human-readable executive summaries,
highlighting excess permissions, escalation risks, and actionable remediation steps.
"""

import os
import sys
import json
import html
import argparse
from datetime import datetime

# Configure UTF-8 encoding for Windows console
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def format_header(title, width=70, char="="):
    return f"\n{char * width}\n  {title}\n{char * width}"


def load_report(filepath):
    if not os.path.exists(filepath):
        print(f"[!] Error: File not found: {filepath}")
        sys.exit(1)
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[!] Error reading JSON file: {e}")
        sys.exit(1)


def generate_summary(data, only_users=False, critical_only=False, max_sample_services=8):
    findings = data.get("findings", [])
    if only_users:
        findings = [f for f in findings if f.get("principal_type") == "User"]

    summary_blocks = []
    
    # Overview metadata
    report_time = data.get("report_time", "N/A")
    source = data.get("source", "N/A")
    stages = ", ".join(data.get("stages_run", ["N/A"]))
    sev = data.get("severity_summary", {})
    
    overview = {
        "report_time": report_time,
        "source": source,
        "stages": stages,
        "total_principals": len(findings),
        "critical": sev.get("critical", 0),
        "high": sev.get("high", 0),
        "medium": sev.get("medium", 0),
        "low": sev.get("low", 0),
    }

    principal_summaries = []

    for p in findings:
        ptype = p.get("principal_type", "Unknown")
        pname = p.get("principal_name", "Unknown")
        arn = p.get("arn", "")
        
        escs = p.get("escalation_paths", [])
        wildcards = p.get("wildcard_findings", [])
        res_wildcards = p.get("resource_wildcard_findings", [])
        unused = p.get("unused_services", [])
        denied = p.get("denied_actions", [])
        sources = p.get("permission_sources", [])

        never_used = [s for s in unused if s.get("status") == "never_used"]
        inactive = [s for s in unused if s.get("status") == "inactive"]

        # Filter out if critical_only requested and no critical/high issues
        has_critical_or_high = bool(escs or wildcards or res_wildcards)
        if critical_only and not has_critical_or_high:
            continue

        item = {
            "type": ptype,
            "name": pname,
            "arn": arn,
            "sources": sources,
            "denied": denied,
            "escalations": escs,
            "wildcards": wildcards,
            "resource_wildcards": res_wildcards,
            "never_used": never_used,
            "inactive": inactive,
        }
        principal_summaries.append(item)

    return overview, principal_summaries


def render_console(overview, principals, max_sample_services=6):
    lines = []
    lines.append(format_header("TỔNG KẾT BÁO CÁO AN TOÀN IAM & LEAST PRIVILEGE", 75, "="))
    lines.append(f"  Thời gian quét : {overview['report_time']}")
    lines.append(f"  Nguồn dữ liệu  : {overview['source']}")
    lines.append(f"  Giai đoạn chạy : {overview['stages']}")
    lines.append(f"  Số đối tượng vi phạm: {len(principals)}")
    lines.append("-" * 75)
    lines.append(
        f"  MỨC ĐỘ RỦI RO: "
        f"CRITICAL: {overview['critical']} | "
        f"HIGH: {overview['high']} | "
        f"MEDIUM: {overview['medium']} | "
        f"LOW: {overview['low']}"
    )
    lines.append("=" * 75)

    if not principals:
        lines.append("\n  [✓] Không có phát hiện nào thỏa mãn tiêu chí lọc.")
        return "\n".join(lines)

    lines.append("\n" + format_header("CHI TIẾT CÁC ĐỐI TƯỢNG CẦN THU HỒI / ĐIỀU CHỈNH QUYỀN", 75, "-"))

    for p in principals:
        icon = "👤" if p["type"] == "User" else "🛡️"
        lines.append(f"\n{icon} [{p['type'].upper()}] {p['name']}")
        lines.append(f"   ARN: {p['arn']}")

        # Permission sources
        if p["sources"]:
            lines.append("   📌 Nguồn cấp quyền:")
            for s in p["sources"]:
                stype = s.get("source_type", "")
                p_name = s.get("policy_name", "unknown")
                if stype == "group_managed":
                    lines.append(f"      - Kế thừa từ Group [{s.get('group_name')}] -> Managed Policy [{p_name}]")
                elif stype == "group_inline":
                    lines.append(f"      - Kế thừa từ Group [{s.get('group_name')}] -> Inline Policy [{p_name}]")
                elif stype == "managed":
                    lines.append(f"      - Gắn trực tiếp Managed Policy [{p_name}]")
                elif stype == "inline":
                    lines.append(f"      - Gắn trực tiếp Inline Policy [{p_name}]")

        # Denied actions
        if p["denied"]:
            lines.append(f"   ⛔ Quyền bị chặn tường minh (Explicit Deny): {len(p['denied'])} hành động {p['denied'][:4]}")

        # Escalation paths
        if p["escalations"]:
            lines.append(f"   🚨 NGUY CƠ LEO THANG ĐẶC QUYỀN ADMIN: {len(p['escalations'])} kịch bản")
            for esc in p["escalations"][:4]:
                lines.append(f"      • [{esc.get('severity').upper()}] {esc.get('escalation_path')}: {esc.get('description')}")
            if len(p["escalations"]) > 4:
                lines.append(f"      • ... và {len(p['escalations']) - 4} kịch bản khác.")

        # Wildcards
        if p["wildcards"]:
            lines.append("   ⚠️  CẤP QUYỀN TOÀN PHẦN (WILDCARD):")
            for w in p["wildcards"]:
                lines.append(f"      • Action: {w.get('action')} ({w.get('finding')})")

        # Resource wildcards
        if p["resource_wildcards"]:
            lines.append(f"   🎯 PHẠM VI TÀI NGUYÊN QUÁ RỘNG (Resource: * trên hành động nhạy cảm): {len(p['resource_wildcards'])} quyền")
            for rw in p["resource_wildcards"][:4]:
                lines.append(f"      • {rw.get('finding')}")
            if len(p["resource_wildcards"]) > 4:
                lines.append(f"      • ... và {len(p['resource_wildcards']) - 4} quyền khác cần thu hẹp ARN.")

        # Unused services
        if p["never_used"]:
            sample_never = [s.get("service_name", "") for s in p["never_used"][:max_sample_services]]
            lines.append(f"   ❌ DƯ THỪA (CHƯA TỪNG DÙNG): {len(p['never_used'])} dịch vụ")
            lines.append(f"      Ví dụ: {', '.join(sample_never)}")
            if len(p["never_used"]) > max_sample_services:
                lines.append(f"      (Và {len(p['never_used']) - max_sample_services} dịch vụ khác cần gỡ bỏ khỏi policy)")

        if p["inactive"]:
            sample_inactive = [f"{s.get('service_name')} ({s.get('days_inactive')} ngày)" for s in p["inactive"][:4]]
            lines.append(f"   ⏳ DỊCH VỤ BỎ HOANG (>90 ngày): {len(p['inactive'])} dịch vụ")
            lines.append(f"      Ví dụ: {', '.join(sample_inactive)}")

        lines.append("   " + "." * 70)

    return "\n".join(lines)


def render_markdown(overview, principals, max_sample_services=8):
    md = []
    md.append("# 📋 Báo Cáo Tóm Tắt Least Privilege & Khuyến Nghị Khắc Phục")
    md.append(f"\n- **Thời gian quét:** `{overview['report_time']}`")
    md.append(f"- **Nguồn dữ liệu:** `{overview['source']}`")
    md.append(f"- **Giai đoạn phân tích:** `{overview['stages']}`")
    md.append(f"- **Tổng số đối tượng cần xem xét:** `{len(principals)}`\n")

    md.append("## 1. Thống kê mức độ rủi ro")
    md.append("\n| Mức độ | Số lượng phát hiện | Ý nghĩa |")
    md.append("|:---|:---:|:---|")
    md.append(f"| 🔴 **Critical** | {overview['critical']} | Nguy cơ chiếm toàn quyền quản trị (Admin) ngay lập tức |")
    md.append(f"| 🟠 **High** | {overview['high']} | Cấp quyền wildcard hoặc thao tác xóa nhạy cảm trên toàn bộ tài nguyên |")
    md.append(f"| 🟡 **Medium** | {overview['medium']} | Dịch vụ được mở quyền nhưng chưa từng được sử dụng |")
    md.append(f"| 🔵 **Low** | {overview['low']} | Dịch vụ không phát sinh lệnh gọi trong hơn 90 ngày |")

    md.append("\n## 2. Chi tiết các đối tượng vi phạm & Hướng khắc phục\n")

    for p in principals:
        icon = "👤" if p["type"] == "User" else "🛡️"
        md.append(f"### {icon} [{p['type']}] `{p['name']}`")
        md.append(f"- **ARN:** `{p['arn']}`")

        # Nguồn quyền
        if p["sources"]:
            md.append("- **Nguồn cấp quyền:**")
            for s in p["sources"]:
                stype = s.get("source_type", "")
                p_name = s.get("policy_name", "unknown")
                if "group" in stype:
                    md.append(f"  - Kế thừa từ Group **`{s.get('group_name')}`** ➔ Policy `{p_name}`")
                else:
                    md.append(f"  - Gắn trực tiếp ➔ Policy `{p_name}`")

        # Vấn đề 1: Leo thang
        if p["escalations"]:
            md.append(f"\n> 🚨 **CẢNH BÁO LEO THANG QUYỀN ({len(p['escalations'])} kịch bản):**")
            for esc in p["escalations"]:
                md.append(f"> - **`{esc.get('escalation_path')}`** ({esc.get('severity')}): {esc.get('description')}")

        # Vấn đề 2: Wildcards
        if p["wildcards"]:
            md.append(f"\n> ⚠️ **CẤP QUYỀN TOÀN PHẦN (WILDCARD):**")
            for w in p["wildcards"]:
                md.append(f"> - Action `{w.get('action')}`: {w.get('finding')}")

        # Vấn đề 3: Resource wildcards
        if p["resource_wildcards"]:
            md.append(f"\n- **Phạm vi tài nguyên quá rộng ({len(p['resource_wildcards'])} quyền):**")
            for rw in p["resource_wildcards"][:max_sample_services]:
                md.append(f"  - `{rw.get('action')}`: Cần giới hạn từ `Resource: *` về ARN cụ thể.")
            if len(p["resource_wildcards"]) > max_sample_services:
                md.append(f"  - *... và {len(p['resource_wildcards']) - max_sample_services} quyền khác.*")

        # Vấn đề 4: Quyền dư thừa
        if p["never_used"]:
            sample_never = [f"`{s.get('service_name')}`" for s in p["never_used"][:max_sample_services]]
            md.append(f"\n- ❌ **Quyền dư thừa (Chưa từng dùng):** `{len(p['never_used'])}` dịch vụ")
            md.append(f"  - *Ví dụ:* {', '.join(sample_never)}")
            if len(p["never_used"]) > max_sample_services:
                md.append(f"  - *(Gợi ý: Cần gỡ bỏ toàn bộ {len(p['never_used'])} dịch vụ này khỏi policy)*")

        if p["inactive"]:
            sample_inact = [f"`{s.get('service_name')}` ({s.get('days_inactive')} ngày)" for s in p["inactive"][:5]]
            md.append(f"- ⏳ **Dịch vụ bỏ hoang (>90 ngày):** `{len(p['inactive'])}` dịch vụ ({', '.join(sample_inact)})")

        md.append("\n---\n")

    return "\n".join(md)


def render_html(overview, principals, max_sample_services=12):
    """Render a standalone, beautiful HTML dashboard report."""
    def esc(text):
        return html.escape(str(text)) if text is not None else ""

    cards_html = []
    for p in principals:
        icon = "👤" if p["type"] == "User" else "🛡️"
        badge_type_class = "badge-user" if p["type"] == "User" else "badge-role"

        # Permission sources
        sources_html = ""
        if p["sources"]:
            src_items = []
            for s in p["sources"]:
                stype = s.get("source_type", "")
                p_name = esc(s.get("policy_name", "unknown"))
                if "group" in stype:
                    src_items.append(f"<li>Kế thừa từ Group <strong>{esc(s.get('group_name'))}</strong> ➔ Policy <code>{p_name}</code></li>")
                else:
                    src_items.append(f"<li>Gắn trực tiếp ➔ Policy <code>{p_name}</code></li>")
            sources_html = f"""
            <div class="meta-section">
                <strong>📌 Nguồn cấp quyền:</strong>
                <ul class="source-list">{''.join(src_items)}</ul>
            </div>
            """

        # Explicit Deny
        deny_html = ""
        if p["denied"]:
            deny_items = "".join(f"<span class='pill pill-deny'>{esc(d)}</span>" for d in p["denied"])
            deny_html = f"""
            <div class="meta-section">
                <strong>⛔ Quyền bị chặn tường minh (Explicit Deny):</strong>
                <div class="pill-container">{deny_items}</div>
            </div>
            """

        # Escalation paths
        esc_html = ""
        if p["escalations"]:
            items = []
            for e in p["escalations"]:
                sev_cls = "badge-critical" if e.get("severity") == "critical" else "badge-high"
                items.append(
                    f"<li><span class='badge {sev_cls}'>{esc(e.get('severity').upper())}</span> "
                    f"<strong>{esc(e.get('escalation_path'))}</strong>: {esc(e.get('description'))}</li>"
                )
            esc_html = f"""
            <div class="alert-box alert-critical">
                <div class="alert-title">🚨 NGUY CƠ LEO THANG ĐẶC QUYỀN ADMIN ({len(p['escalations'])} kịch bản)</div>
                <ul class="vuln-list">{''.join(items)}</ul>
            </div>
            """

        # Wildcards
        wc_html = ""
        if p["wildcards"]:
            items = []
            for w in p["wildcards"]:
                items.append(f"<li>Action <code>{esc(w.get('action'))}</code>: {esc(w.get('finding'))}</li>")
            wc_html = f"""
            <div class="alert-box alert-warning">
                <div class="alert-title">⚠️ CẤP QUYỀN TOÀN PHẦN (WILDCARD)</div>
                <ul class="vuln-list">{''.join(items)}</ul>
            </div>
            """

        # Resource wildcards
        rw_html = ""
        if p["resource_wildcards"]:
            items = []
            for rw in p["resource_wildcards"][:max_sample_services]:
                items.append(f"<li><code>{esc(rw.get('action'))}</code>: {esc(rw.get('finding'))}</li>")
            extra = ""
            if len(p["resource_wildcards"]) > max_sample_services:
                extra = f"<p class='text-muted'>... và {len(p['resource_wildcards']) - max_sample_services} quyền khác cần thu hẹp ARN.</p>"
            rw_html = f"""
            <div class="alert-box alert-purple">
                <div class="alert-title">🎯 PHẠM VI TÀI NGUYÊN QUÁ RỘNG (Resource: * trên thao tác nhạy cảm - {len(p['resource_wildcards'])} quyền)</div>
                <ul class="vuln-list">{''.join(items)}</ul>
                {extra}
            </div>
            """

        # Unused services
        unused_html = ""
        if p["never_used"]:
            pills = "".join(f"<span class='pill pill-never'>{esc(s.get('service_name'))}</span>" for s in p["never_used"][:max_sample_services])
            extra = ""
            if len(p["never_used"]) > max_sample_services:
                extra = f"<span class='text-muted'>+ {len(p['never_used']) - max_sample_services} dịch vụ khác cần gỡ bỏ khỏi policy.</span>"
            unused_html = f"""
            <div class="alert-box alert-gray">
                <div class="alert-title">❌ DƯ THỪA (CHƯA TỪNG SỬ DỤNG): {len(p['never_used'])} dịch vụ</div>
                <div class="pill-container">{pills}</div>
                {extra}
            </div>
            """

        # Inactive services
        inact_html = ""
        if p["inactive"]:
            items = "".join(f"<li>{esc(s.get('service_name'))} <span class='badge badge-low'>không dùng {s.get('days_inactive')} ngày</span></li>" for s in p["inactive"][:6])
            inact_html = f"""
            <div class="alert-box alert-blue">
                <div class="alert-title">⏳ DỊCH VỤ BỎ HOANG (>90 ngày): {len(p['inactive'])} dịch vụ</div>
                <ul class="vuln-list">{items}</ul>
            </div>
            """

        card = f"""
        <div class="principal-card">
            <div class="card-header">
                <div>
                    <span class="badge {badge_type_class}">{esc(p['type'].upper())}</span>
                    <span class="principal-name">{icon} {esc(p['name'])}</span>
                </div>
                <div class="principal-arn">{esc(p['arn'])}</div>
            </div>
            <div class="card-body">
                {sources_html}
                {deny_html}
                {esc_html}
                {wc_html}
                {rw_html}
                {unused_html}
                {inact_html}
            </div>
        </div>
        """
        cards_html.append(card)

    template = f"""<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Báo Cáo Least Privilege & An Toàn AWS IAM</title>
    <style>
        :root {{
            --bg: #f8fafc;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --critical: #ef4444;
            --high: #f97316;
            --medium: #f59e0b;
            --low: #3b82f6;
            --success: #10b981;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            line-height: 1.6;
            margin: 0;
            padding: 24px;
        }}
        .container {{
            max-width: 1100px;
            margin: 0 auto;
        }}
        header {{
            background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
            color: #ffffff;
            padding: 32px;
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1);
            margin-bottom: 28px;
        }}
        header h1 {{
            margin: 0 0 12px 0;
            font-size: 26px;
            font-weight: 700;
        }}
        header .meta {{
            font-size: 14px;
            color: #94a3b8;
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 16px;
            margin-bottom: 32px;
        }}
        .stat-card {{
            background: var(--card-bg);
            padding: 20px;
            border-radius: 12px;
            border: 1px solid var(--border);
            border-left-width: 5px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.02);
        }}
        .stat-card.stat-critical {{ border-left-color: var(--critical); }}
        .stat-card.stat-high {{ border-left-color: var(--high); }}
        .stat-card.stat-medium {{ border-left-color: var(--medium); }}
        .stat-card.stat-low {{ border-left-color: var(--low); }}
        .stat-number {{
            font-size: 32px;
            font-weight: 800;
            margin-bottom: 4px;
        }}
        .stat-critical .stat-number {{ color: var(--critical); }}
        .stat-high .stat-number {{ color: var(--high); }}
        .stat-medium .stat-number {{ color: var(--medium); }}
        .stat-low .stat-number {{ color: var(--low); }}
        .stat-label {{
            font-size: 14px;
            font-weight: 600;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}
        .stat-desc {{
            font-size: 12px;
            color: var(--text-muted);
            margin-top: 4px;
        }}
        .section-title {{
            font-size: 20px;
            font-weight: 700;
            margin: 32px 0 16px 0;
            display: flex;
            align-items: center;
            gap: 8px;
        }}
        .principal-card {{
            background: var(--card-bg);
            border-radius: 14px;
            border: 1px solid var(--border);
            margin-bottom: 24px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
            overflow: hidden;
        }}
        .card-header {{
            background: #f1f5f9;
            padding: 16px 20px;
            border-bottom: 1px solid var(--border);
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 12px;
        }}
        .principal-name {{
            font-size: 18px;
            font-weight: 700;
            margin-left: 8px;
        }}
        .principal-arn {{
            font-family: monospace;
            font-size: 12px;
            color: var(--text-muted);
            background: #ffffff;
            padding: 4px 8px;
            border-radius: 6px;
            border: 1px solid var(--border);
        }}
        .card-body {{
            padding: 20px;
        }}
        .meta-section {{
            margin-bottom: 16px;
            font-size: 14px;
        }}
        .source-list {{
            margin: 6px 0 0 0;
            padding-left: 20px;
            color: #334155;
        }}
        .alert-box {{
            padding: 14px 18px;
            border-radius: 10px;
            margin-bottom: 14px;
            font-size: 14px;
        }}
        .alert-title {{
            font-weight: 700;
            margin-bottom: 8px;
        }}
        .alert-critical {{
            background: #fef2f2;
            border: 1px solid #fecaca;
            color: #991b1b;
        }}
        .alert-warning {{
            background: #fffbeb;
            border: 1px solid #fde68a;
            color: #92400e;
        }}
        .alert-purple {{
            background: #faf5ff;
            border: 1px solid #e9d5ff;
            color: #6b21a8;
        }}
        .alert-gray {{
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            color: #334155;
        }}
        .alert-blue {{
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            color: #1e40af;
        }}
        .vuln-list {{
            margin: 0;
            padding-left: 20px;
        }}
        .vuln-list li {{
            margin-bottom: 4px;
        }}
        .badge {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 6px;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
        }}
        .badge-user {{ background: #dbeafe; color: #1e40af; }}
        .badge-role {{ background: #f3e8ff; color: #6b21a8; }}
        .badge-critical {{ background: #fee2e2; color: #b91c1c; }}
        .badge-high {{ background: #ffedd5; color: #c2410c; }}
        .badge-low {{ background: #e0f2fe; color: #0369a1; }}
        .pill-container {{
            display: flex;
            flex-wrap: wrap;
            gap: 6px;
            margin: 8px 0;
        }}
        .pill {{
            display: inline-block;
            padding: 4px 10px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 500;
        }}
        .pill-never {{ background: #fee2e2; color: #991b1b; border: 1px solid #fca5a5; }}
        .pill-deny {{ background: #f1f5f9; color: #475569; border: 1px solid #cbd5e1; }}
        .text-muted {{
            font-size: 13px;
            color: var(--text-muted);
            margin: 4px 0 0 0;
        }}
        code {{
            background: #f1f5f9;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: monospace;
            font-size: 13px;
        }}
        footer {{
            text-align: center;
            font-size: 13px;
            color: var(--text-muted);
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid var(--border);
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🛡️ Báo Cáo Least Privilege & An Toàn AWS IAM</h1>
            <div class="meta">
                <span>🕒 Thời gian quét: <strong>{esc(overview['report_time'])}</strong></span>
                <span>📂 Nguồn: <strong>{esc(overview['source'])}</strong></span>
                <span>⚙️ Giai đoạn: <strong>{esc(overview['stages'])}</strong></span>
            </div>
        </header>

        <div class="stats-grid">
            <div class="stat-card stat-critical">
                <div class="stat-number">{overview['critical']}</div>
                <div class="stat-label">Critical</div>
                <div class="stat-desc">Nguy cơ chiếm toàn quyền Admin ngay lập tức</div>
            </div>
            <div class="stat-card stat-high">
                <div class="stat-number">{overview['high']}</div>
                <div class="stat-label">High</div>
                <div class="stat-desc">Quyền Wildcard hoặc Resource:* trên thao tác xóa</div>
            </div>
            <div class="stat-card stat-medium">
                <div class="stat-number">{overview['medium']}</div>
                <div class="stat-label">Medium</div>
                <div class="stat-desc">Dịch vụ mở quyền nhưng chưa từng được sử dụng</div>
            </div>
            <div class="stat-card stat-low">
                <div class="stat-number">{overview['low']}</div>
                <div class="stat-label">Low</div>
                <div class="stat-desc">Dịch vụ không phát sinh lệnh gọi > 90 ngày</div>
            </div>
        </div>

        <div class="section-title">🔍 Chi Tiết Các Đối Tượng Cần Điều Chỉnh ({len(principals)} Đối Tượng)</div>

        {''.join(cards_html) if cards_html else '<p>Không có đối tượng nào vi phạm theo tiêu chí lọc.</p>'}

        <footer>
            Báo cáo được sinh tự động bởi <strong>AWS IAM Least Privilege Analyzer (scan.py & summarize.py)</strong>.
        </footer>
    </div>
</body>
</html>
"""
    return template


def main():
    parser = argparse.ArgumentParser(
        description="AWS IAM Least Privilege Report Summarizer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Summarize default report to console:
  python summarize.py

  # Summarize a specific scan report:
  python summarize.py -i live_least_privilege_report.json

  # Focus only on IAM Users:
  python summarize.py --only-users

  # Focus only on Critical and High risks:
  python summarize.py --critical-only

  # Export the executive summary to Markdown:
  python summarize.py -i live_least_privilege_report.json --md summary_report.md

  # Export a standalone visual HTML dashboard:
  python summarize.py -i live_least_privilege_report.json --html dashboard.html
        """
    )
    parser.add_argument("-i", "--input", default="live_least_privilege_report.json",
                        help="Input report JSON file (default: live_least_privilege_report.json)")
    parser.add_argument("--only-users", action="store_true",
                        help="Filter out IAM roles and only display IAM users")
    parser.add_argument("--critical-only", action="store_true",
                        help="Only show principals with Critical/High privilege escalation or wildcard issues")
    parser.add_argument("--md", "--markdown", dest="md_output",
                        help="Export human-readable summary to a Markdown file")
    parser.add_argument("--html", dest="html_output",
                        help="Export a beautiful standalone visual HTML dashboard report")

    args = parser.parse_args()

    # Fallback to alternative filename if default not found
    if not os.path.exists(args.input) and args.input == "live_least_privilege_report.json":
        if os.path.exists("least_privilege_report.json"):
            args.input = "least_privilege_report.json"

    data = load_report(args.input)
    overview, principals = generate_summary(
        data,
        only_users=args.only_users,
        critical_only=args.critical_only
    )

    # Render console
    console_text = render_console(overview, principals)
    print(console_text)

    # Export to markdown if requested
    if args.md_output:
        md_text = render_markdown(overview, principals)
        with open(args.md_output, "w", encoding="utf-8") as f:
            f.write(md_text)
        print(f"\n[+] Báo cáo tóm tắt Markdown đã được lưu tại: {args.md_output}")

    # Export to HTML dashboard if requested
    if args.html_output:
        html_text = render_html(overview, principals)
        with open(args.html_output, "w", encoding="utf-8") as f:
            f.write(html_text)
        print(f"[+] Báo cáo Dashboard HTML trực quan đã được lưu tại: {args.html_output}")


if __name__ == "__main__":
    main()

